version: '3.9'

services:

  # FHE ENCRYPTOR
  fhe-encryptor:
    build: ./HEHAEnc
    container_name: fhe-enc
    volumes:
      - ./HEHAEnc/build/data:/bdt/build/data
      - encrypted_data:/bdt/build/results
      - cryptocontext:/bdt/build/cryptocontext
      - private_key:/bdt/build/private_data
      - ./HEHAEnc/build/timing/:/bdt/build/timing
    command: tail -f /dev/null
    networks:
      - soteria_network

  # FHE MAIN (GPU, stays running until you exec into it)
  fhe-main:
    build: ./HEHAMain
    container_name: heha-main
    volumes:
      - analytics_results:/bdt/build/results
      - encrypted_data:/bdt/build/data
      - ./HEHAMain/build/timing/:/bdt/build/timing
    command: tail -f /dev/null   # keeps container running, does NOT start main process
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - soteria_network

  # FHE DECRYPTOR
  fhe-decryptor:
    build: ./HEHADec
    container_name: fhe-dec
    command: tail -f /dev/null
    volumes:
      - analytics_results:/bdt/build/data
      - cryptocontext:/bdt/build/cryptocontext/
      - private_key:/bdt/build/private_data
      - ./HEHADec/build/timing/:/bdt/build/timing
    networks:
      - soteria_network

networks:
  soteria_network:
    name: "soteria_network"
    external: true

volumes:
  encrypted_data:
  private_key:
  analytics_results:
  cryptocontext:
